// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SportsBetting.Data;

#nullable disable

namespace SportsBetting.Data.Migrations
{
    [DbContext(typeof(SportsBettingDbContext))]
    [Migration("20251115164828_CreateExchangeTables")]
    partial class CreateExchangeTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SportsBetting.Domain.Entities.Bet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ActualPayout")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("ActualPayout");

                    b.Property<string>("ActualPayoutCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<int>("BetMode")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LineLockId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ProposedOdds")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("CombinedOdds", "SportsBetting.Domain.Entities.Bet.CombinedOdds#Odds", b1 =>
                        {
                            b1.Property<decimal>("DecimalValue")
                                .HasPrecision(10, 4)
                                .HasColumnType("numeric(10,4)")
                                .HasColumnName("CombinedOddsDecimal");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PotentialPayout", "SportsBetting.Domain.Entities.Bet.PotentialPayout#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("PotentialPayout");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("PotentialPayoutCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Stake", "SportsBetting.Domain.Entities.Bet.Stake#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Stake");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("StakeCurrency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id");

                    b.HasIndex("LineLockId")
                        .HasDatabaseName("IX_Bets_LineLockId");

                    b.HasIndex("PlacedAt")
                        .HasDatabaseName("IX_Bets_PlacedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Bets_Status");

                    b.HasIndex("TicketNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Bets_TicketNumber");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Bets_UserId");

                    b.HasIndex("UserId", "PlacedAt")
                        .HasDatabaseName("IX_Bets_UserId_PlacedAt");

                    b.ToTable("Bets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bets_ActualPayout_NonNegative", "\"ActualPayout\" IS NULL OR \"ActualPayout\" >= 0");

                            t.HasCheckConstraint("CK_Bets_CombinedOdds_MinimumOne", "\"CombinedOddsDecimal\" >= 1.0");

                            t.HasCheckConstraint("CK_Bets_PotentialPayout_NonNegative", "\"PotentialPayout\" >= 0");

                            t.HasCheckConstraint("CK_Bets_Stake_Positive", "\"Stake\" > 0");
                        });
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.BetMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackBetId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LayBetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MatchedOdds")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MatchedStake")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WinnerBetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BackBetId");

                    b.HasIndex("IsSettled")
                        .HasFilter("\"IsSettled\" = false");

                    b.HasIndex("LayBetId");

                    b.ToTable("BetMatches");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.BetSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BetId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("Line")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OutcomeId")
                        .HasColumnType("uuid");

                    b.Property<string>("OutcomeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty<Dictionary<string, object>>("LockedOdds", "SportsBetting.Domain.Entities.BetSelection.LockedOdds#Odds", b1 =>
                        {
                            b1.Property<decimal>("DecimalValue")
                                .HasPrecision(10, 4)
                                .HasColumnType("numeric(10,4)")
                                .HasColumnName("LockedOddsDecimal");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BetId")
                        .HasDatabaseName("IX_BetSelections_BetId");

                    b.HasIndex("BetId1");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_BetSelections_EventId");

                    b.HasIndex("MarketId")
                        .HasDatabaseName("IX_BetSelections_MarketId");

                    b.HasIndex("OutcomeId")
                        .HasDatabaseName("IX_BetSelections_OutcomeId");

                    b.HasIndex("Result")
                        .HasDatabaseName("IX_BetSelections_Result");

                    b.ToTable("BetSelections", (string)null);
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.ConsensusOdds", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageOdds")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaxOdds")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinOdds")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OutcomeId")
                        .HasColumnType("uuid");

                    b.Property<int>("SampleSize")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OutcomeId", "ExpiresAt");

                    b.ToTable("ConsensusOdds");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("FinalScore")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("FinalScore");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ScheduledStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Venue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId")
                        .HasDatabaseName("IX_Events_AwayTeamId");

                    b.HasIndex("HomeTeamId")
                        .HasDatabaseName("IX_Events_HomeTeamId");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("IX_Events_LeagueId");

                    b.HasIndex("ScheduledStartTime")
                        .HasDatabaseName("IX_Events_ScheduledStartTime");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Events_Status");

                    b.HasIndex("LeagueId", "ScheduledStartTime")
                        .HasDatabaseName("IX_Events_LeagueId_ScheduledStartTime");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.ExchangeBet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MatchedStake")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProposedOdds")
                        .HasColumnType("numeric");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalStake")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnmatchedStake")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BetId")
                        .IsUnique();

                    b.HasIndex("State")
                        .HasFilter("\"State\" IN ('Unmatched', 'PartiallyMatched')");

                    b.ToTable("ExchangeBets");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SportId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Leagues_Code");

                    b.HasIndex("SportId")
                        .HasDatabaseName("IX_Leagues_SportId");

                    b.HasIndex("SportId1");

                    b.ToTable("Leagues", (string)null);
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.LineLock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssociatedBetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Line")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("LockNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OutcomeId")
                        .HasColumnType("uuid");

                    b.Property<string>("OutcomeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("LockFee", "SportsBetting.Domain.Entities.LineLock.LockFee#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("LockFee");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("LockFeeCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("LockedOdds", "SportsBetting.Domain.Entities.LineLock.LockedOdds#Odds", b1 =>
                        {
                            b1.Property<decimal>("DecimalValue")
                                .HasPrecision(10, 4)
                                .HasColumnType("numeric(10,4)")
                                .HasColumnName("LockedOddsDecimal");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("MaxStake", "SportsBetting.Domain.Entities.LineLock.MaxStake#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("MaxStake");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("MaxStakeCurrency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id");

                    b.HasIndex("AssociatedBetId")
                        .HasDatabaseName("IX_LineLocks_AssociatedBetId");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_LineLocks_EventId");

                    b.HasIndex("ExpirationTime")
                        .HasDatabaseName("IX_LineLocks_ExpirationTime");

                    b.HasIndex("LockNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_LineLocks_LockNumber");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_LineLocks_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_LineLocks_UserId");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_LineLocks_UserId_Status");

                    b.ToTable("LineLocks", (string)null);
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.Market", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventId1")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ExchangeCommissionRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("boolean");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_Markets_EventId");

                    b.HasIndex("EventId1");

                    b.HasIndex("IsOpen")
                        .HasDatabaseName("IX_Markets_IsOpen");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Markets_Type");

                    b.HasIndex("EventId", "Type")
                        .HasDatabaseName("IX_Markets_EventId_Type");

                    b.ToTable("Markets", (string)null);
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.Outcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsVoid")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsWinner")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Line")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MarketId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.ComplexProperty<Dictionary<string, object>>("CurrentOdds", "SportsBetting.Domain.Entities.Outcome.CurrentOdds#Odds", b1 =>
                        {
                            b1.Property<decimal>("DecimalValue")
                                .HasPrecision(10, 4)
                                .HasColumnType("numeric(10,4)")
                                .HasColumnName("CurrentOddsDecimal");
                        });

                    b.HasKey("Id");

                    b.HasIndex("IsVoid")
                        .HasDatabaseName("IX_Outcomes_IsVoid");

                    b.HasIndex("IsWinner")
                        .HasDatabaseName("IX_Outcomes_IsWinner");

                    b.HasIndex("MarketId")
                        .HasDatabaseName("IX_Outcomes_MarketId");

                    b.HasIndex("MarketId1");

                    b.ToTable("Outcomes", (string)null);
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.Sport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Sports_Code");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Sports_Name");

                    b.ToTable("Sports", (string)null);
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeagueId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Teams_Code");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("IX_Teams_LeagueId");

                    b.HasIndex("LeagueId1");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Teams_Name");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Amount", "SportsBetting.Domain.Entities.Transaction.Amount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("Currency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("BalanceAfter", "SportsBetting.Domain.Entities.Transaction.BalanceAfter#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("BalanceAfter");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("BalanceAfterCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("BalanceBefore", "SportsBetting.Domain.Entities.Transaction.BalanceBefore#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("BalanceBefore");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("BalanceBeforeCurrency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Transactions_CreatedAt");

                    b.HasIndex("ReferenceId")
                        .HasDatabaseName("IX_Transactions_ReferenceId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Transactions_Status");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Transactions_Type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Transactions_UserId");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_Transactions_UserId_CreatedAt");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_Amount_Positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_Transactions_BalanceAfter_NonNegative", "\"BalanceAfter\" >= 0");

                            t.HasCheckConstraint("CK_Transactions_BalanceBefore_NonNegative", "\"BalanceBefore\" >= 0");
                        });
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailVerificationTokenExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Users_CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Balance", "SportsBetting.Domain.Entities.Wallet.Balance#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Balance");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("Currency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalBet", "SportsBetting.Domain.Entities.Wallet.TotalBet#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TotalBet");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("TotalBetCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalDeposited", "SportsBetting.Domain.Entities.Wallet.TotalDeposited#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TotalDeposited");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("TotalDepositedCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalWithdrawn", "SportsBetting.Domain.Entities.Wallet.TotalWithdrawn#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TotalWithdrawn");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("TotalWithdrawnCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalWon", "SportsBetting.Domain.Entities.Wallet.TotalWon#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TotalWon");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("TotalWonCurrency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id");

                    b.HasIndex("LastUpdatedAt")
                        .HasDatabaseName("IX_Wallets_LastUpdatedAt");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Wallets_UserId");

                    b.ToTable("Wallets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Wallets_Balance_NonNegative", "\"Balance\" >= 0");

                            t.HasCheckConstraint("CK_Wallets_TotalBet_NonNegative", "\"TotalBet\" >= 0");

                            t.HasCheckConstraint("CK_Wallets_TotalDeposited_NonNegative", "\"TotalDeposited\" >= 0");

                            t.HasCheckConstraint("CK_Wallets_TotalWithdrawn_NonNegative", "\"TotalWithdrawn\" >= 0");

                            t.HasCheckConstraint("CK_Wallets_TotalWon_NonNegative", "\"TotalWon\" >= 0");
                        });
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.Bet", b =>
                {
                    b.HasOne("SportsBetting.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.BetMatch", b =>
                {
                    b.HasOne("SportsBetting.Domain.Entities.ExchangeBet", "BackBet")
                        .WithMany("MatchesAsBack")
                        .HasForeignKey("BackBetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsBetting.Domain.Entities.ExchangeBet", "LayBet")
                        .WithMany("MatchesAsLay")
                        .HasForeignKey("LayBetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BackBet");

                    b.Navigation("LayBet");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.BetSelection", b =>
                {
                    b.HasOne("SportsBetting.Domain.Entities.Bet", null)
                        .WithMany()
                        .HasForeignKey("BetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsBetting.Domain.Entities.Bet", null)
                        .WithMany("Selections")
                        .HasForeignKey("BetId1");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.ConsensusOdds", b =>
                {
                    b.HasOne("SportsBetting.Domain.Entities.Outcome", "Outcome")
                        .WithMany()
                        .HasForeignKey("OutcomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outcome");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.Event", b =>
                {
                    b.HasOne("SportsBetting.Domain.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsBetting.Domain.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.ExchangeBet", b =>
                {
                    b.HasOne("SportsBetting.Domain.Entities.Bet", "Bet")
                        .WithOne()
                        .HasForeignKey("SportsBetting.Domain.Entities.ExchangeBet", "BetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bet");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.League", b =>
                {
                    b.HasOne("SportsBetting.Domain.Entities.Sport", null)
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsBetting.Domain.Entities.Sport", null)
                        .WithMany("Leagues")
                        .HasForeignKey("SportId1");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.LineLock", b =>
                {
                    b.HasOne("SportsBetting.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.Market", b =>
                {
                    b.HasOne("SportsBetting.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsBetting.Domain.Entities.Event", null)
                        .WithMany("Markets")
                        .HasForeignKey("EventId1");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.Outcome", b =>
                {
                    b.HasOne("SportsBetting.Domain.Entities.Market", null)
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsBetting.Domain.Entities.Market", null)
                        .WithMany("Outcomes")
                        .HasForeignKey("MarketId1");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SportsBetting.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.Team", b =>
                {
                    b.HasOne("SportsBetting.Domain.Entities.League", null)
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsBetting.Domain.Entities.League", null)
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId1");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("SportsBetting.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("SportsBetting.Domain.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("SportsBetting.Domain.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.Bet", b =>
                {
                    b.Navigation("Selections");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.Event", b =>
                {
                    b.Navigation("Markets");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.ExchangeBet", b =>
                {
                    b.Navigation("MatchesAsBack");

                    b.Navigation("MatchesAsLay");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.League", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.Market", b =>
                {
                    b.Navigation("Outcomes");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.Sport", b =>
                {
                    b.Navigation("Leagues");
                });

            modelBuilder.Entity("SportsBetting.Domain.Entities.User", b =>
                {
                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
